export const ALLOWED_ACTIONS = [
  'create_campaign',
  'generate_strategy',
  'approve_strategy',
  'reject_strategy',
  'generate_campaign_strategy',
  'approve_campaign_strategy',
  'generate_7_day_plan',
  'approve_7_day_plan',
  'create_content_packages_from_daily_plan',
  'get_campaign_day_status',
  'start_campaign_day',
  'generate_content_for_package',
  'list_content_versions',
  'select_content_version',
  'revise_content',
  'approve_content',
  'request_content_revision',
  'get_content_readiness',
  'get_character_for_campaign',
  'list_character_loras',
  'create_asset_generation_job',
  'get_generation_job',
  'retry_generation_job',
  'list_assets_for_content',
  'attach_asset_to_content',
  'set_primary_asset',
  'approve_asset',
  'generate_content',
  'rewrite_content',
  'save_draft',
  'import_x_reference',
  'upload_reference_asset',
  'generate_character_image',
  'generate_character_video',
  'poll_asset_status',
  'review_generated_asset',
  'regenerate_asset',
  'finalize_content_package',
  'approve_publish',
  'reject_publish',
  'run_publish_preflight',
  'approve_publish_task',
  'schedule_publish_task',
  'execute_publish_task',
  'retry_publish_task',
  'get_publish_result',
  'collect_content_metrics',
  'review_content_performance',
  'create_strategy_adjustment_suggestion',
  'save_campaign_insight',
  'update_account_memory',
  'get_day_review',
  'execute_publish',
  'sync_x_account',
  'analyze_account',
];

export function validateActionRequest(body) {
  if (!body || typeof body !== 'object') throw new Error('请求体为空。');
  if (!body.run_id) throw new Error('缺少 run_id。');
  if (!body.user_id) throw new Error('缺少 user_id。');
  if (!ALLOWED_ACTIONS.includes(body.action)) throw new Error('不允许的 action。');
  if (body.payload && JSON.stringify(body.payload).length > 64 * 1024) throw new Error('payload 过大。');
  return body;
}
